name: Terraform Feature CI

on:
  push:
    branches:
      - feature/terraform-ci

  pull_request:
    branches:
      - feature/terraform-ci

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:

  terraform-check:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/asset-dev

    steps:

      # --------------------------------------------------
      # 1. Checkout
      # --------------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4


      # --------------------------------------------------
      # 2. Setup Terraform
      # --------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8


      # --------------------------------------------------
      # 3. Terraform Format Check
      # --------------------------------------------------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive


      # --------------------------------------------------
      # 4. Terraform Init
      # --------------------------------------------------
      - name: Terraform Init
        run: terraform init -backend=false


      # --------------------------------------------------
      # 5. Terraform Validate
      # --------------------------------------------------
      - name: Terraform Validate
        run: terraform validate


      # --------------------------------------------------
      # 6. Setup TFLint
      # --------------------------------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4


      # --------------------------------------------------
      # 7. Run TFLint
      # --------------------------------------------------
      - name: Run TFLint
        run: |
          tflint --init
          tflint


      # --------------------------------------------------
      # 8. Run tfsec
      # --------------------------------------------------
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: Environment/asset-dev


      # --------------------------------------------------
      # 9. Run Checkov
      # --------------------------------------------------
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: Environment/asset-dev
          framework: terraform
          quiet: true


      # --------------------------------------------------
      # 10. Run Gitleaks
      # --------------------------------------------------
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # --------------------------------------------------
      # 11. Setup Infracost
      # --------------------------------------------------
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}


      # --------------------------------------------------
      # 12. Infracost Breakdown
      # --------------------------------------------------
      - name: Run Infracost
        run: |
          infracost breakdown \
            --path=. \
            --format=json \
            --out-file=/tmp/infracost.json


      # --------------------------------------------------
      # 13. Display Cost
      # --------------------------------------------------
      - name: Display Infracost
        run: |
          infracost output \
            --path=/tmp/infracost.json \
            --format=table


      # --------------------------------------------------
      # 14. Terraform Plan
      # --------------------------------------------------
      - name: Terraform Plan
        run: |
          terraform plan \
            -out=tfplan


      # --------------------------------------------------
      # 15. Save Terraform Plan
      # --------------------------------------------------
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Environment/asset-dev/tfplan